name: Build MS Executable

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          # The server is running 3.10.0 but the script has problems with 3.10 so reverting to 3.9
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      
      #- name: Run Pytest
        #run: |
          # pytest

      - name: Replace placeholders with secrets
        run: |
          sed -i 's/<DB_SERVER>/${{ secrets.DB_SERVER }}/g' src/streamqueue.py
          sed -i 's/<DB_DATABASE>/${{ secrets.DB_DATABASE }}/g' src/streamqueue.py
          sed -i 's/<DB_USERNAME>/${{ secrets.DB_USERNAME }}/g' src/streamqueue.py
          sed -i 's/<DB_PASSWORD>/${{ secrets.DB_PASSWORD }}/g' src/streamqueue.py
          sed -i 's/<API_KEY>/${{ secrets.API_KEY }}/g' src/streamqueue.py

      - name: Create the installable
        # Create the exe and capture the path to the resulting file
        run: |
          pyinstaller src/streamqueue.py
          
      - name: Archive installable
        uses: actions/upload-artifact@v3
        with:
          name: streamqueue-installable
          path: dist

